//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDT.Plugins.Custom {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class MetaDataPluginSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MetaDataPluginSettings defaultInstance = ((MetaDataPluginSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MetaDataPluginSettings())));
        
        public static MetaDataPluginSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableVerticalCardInfoBars {
            get {
                return ((bool)(this["EnableVerticalCardInfoBars"]));
            }
            set {
                this["EnableVerticalCardInfoBars"] = value;
            }
        }
    }
}
